enable-magisk-update = true
parallel-jobs = 1

# Morphe
[YouTube-Morphe]
app-name = "YouTube"
excluded-patches = "'Custom branding'"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
